version: 1.0.{build}
os: Visual Studio 2013
configuration: Release
build:
  project: src\ClinicalInformationSystem.sln
  verbosity: normal
before_build:
- nuget restore
after_test: 
- .\packages\OpenCover.4.6.519\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\test\Application\Business Components Test\bin\Debug\Business Components Test.dll" -filter:"+[Business Components Test]*  -[Business Components Test]Business Components Test.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\BusinessComponentsTest_coverage.xml
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "MyProject_coverage.xml"